apiVersion: v1
kind: Service
metadata:
  name: workload-app
  namespace: java-app-dev
spec:
  type: ClusterIP
  selector:
    app: workload-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080

